# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20150120_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone_type',
            field=models.IntegerField(choices=[(0, b'Home'), (1, b'Mobile'), (2, b'Work'), (3, b'Other')], default=0),
        ),
    ]
